from .camera_frame import CameraFrame
from .connection_frame import ConnectionFrame
from .console_frame import ConsoleFrame
from .info_frame import InfoFrame
from .locations_frame import LocationsFrame
from .procedure_builder_frame import ProcedureBuilderFrame
from .procedure_log_frame import ProcedureLogFrame
from .spectrometer_frame import SpectrometerFrame
from .tab_view_frame import TabViewFrame